spring:
  datasource:
    name: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/industry_model?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
logging:
  level:
    com.wey.ten.era.application: debug
    org.springframework: warn