server:
  port: 9999
spring:
  application:
    name: com.wey.ten.era.gateway
  cloud:
    gateway:
      routes:
      - id: com.wey.ten.era.models
        uri: http://127.0.0.1:8081 
        predicates:
        - Path=/models/**
      - id: com.wey.ten.era.rbac
        uri: http://127.0.0.1:8082
        predicates:
        - Path=/user/**
#      - id: base-service
#        uri: lb://base-service
#        predicates:
#          - Path=/a/base/**