server:
  port: 8082
spring:
  application:
    name: com.wey.ten.era.rbac
  profiles: 
     active: test
  cloud:
    config:
      name: era #文件前缀名称
      profile: config-dev # 服务环境名称 例如 {name}-{profile} = exploit-config.yml
      discovery:
        enabled: true # 是否启用服务发现
        service-id: com.wey.ten.era.config # 配置中心的服务id,即spring.application.name
      username: rbac
      password: password123
mybatis:
  type-aliases-package: com.wey.ten.era.rbac.**.entity
  mapper-locations: classpath:mapper/**/*Mapper.xml
  config-location: classpath:mapper/mybatis-config.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/