spring:
  datasource:
    name: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rbac?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowMultiQueries=true&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
  mail:
    username: Wc20180510@163.com
    password: GZTAOTVUAWAKKUFU
    host: smtp.163.com
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
           auth: true
           socketFactory:
              class: javax.net.ssl.SSLSocketFactory
logging:
  level:
    com.wey.ten.era.rbac: debug
    org.springframework: warn