server:
  port: 8089
spring:
  profiles:
    active: git
  application:
    name: ConfigServer  # 应用名称
  cloud:
     config:
        server:
          git: #设置git仓库的位置，上面有配置文件。
             uri: https://gitee.com/**.git
             username: #xxx
             password: #xxx
          svn: 
             uri: svn://127.0.0.1
             username: 
             password: 
             default-label: master
          health:      
             #关闭配置仓库的健康检查
             enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
      eureka:
management:
  endpoints:
    web:
      expose: "*"
